BTL - MVC/Areas/Admin/Controllers/SanPhamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BTL___MVC.Database;
using static System.Net.WebRequestMethods;

namespace BTL___MVC.Areas.Admin.Controllers
{
    public class SanPhamsController : Controller
    {
        private BTL_MVCEntities db = new BTL_MVCEntities();

        // GET: Admin/SanPhams
        public ActionResult Index()
        {
            //var sanPhams = db.SanPhams.Include(s => s.LoaiSanPham);
            return View();
        }
        public ActionResult getData()
        {
            db.Configuration.ProxyCreationEnabled = false;
            var sanpham = db.SanPhams.ToList();
            return Json(sanpham, JsonRequestBehavior.AllowGet);
        }
        //public ActionResult getByID(int id)
        //{
        //    SanPham sanPham = db.SanPhams.Find(id);
        //    return Json(sanPham, JsonRequestBehavior.AllowGet);
        //}
        public JsonResult GetByID(int id)
        {
            var all = db.SanPhams.ToList();
            var kq = (from x in all
                      where x.Sanpham_id == id
                      select new
                      {
                          Sanpham_id = x.Sanpham_id,
                          Maloai_id = x.Maloai_id,
                          Tensanpham = x.Tensanpham,
                          Anh = x.Anh,
                          Soluong = x.Soluong,
                          Gia = x.Gia,
                          Mota = x.Mota,
                          Kichco = x.Kichco,
                          Dophangiai = x.Dophangiai,
                          Giakhuyenmai = x.Giakhuyenmai,
                          Viewcount = x.Viewcount,
                          ReducePrice = x.ReducePrice,
                      }).FirstOrDefault();
            return Json(kq, JsonRequestBehavior.AllowGet);

        }

        public ActionResult ThemSP()
        {
            ViewBag.Maloai_id = new SelectList(db.LoaiSanPhams, "Maloai_id", "Tenloai");

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ThemSP([Bind(Include = "sanpham_id,maloai_id,tensanpham,anh,soluong,gia,mota,kichco,dophangiai,giakhuyenmai,Viewcount,ReducePrice")] SanPham sanPham)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.SanPhams.Add(sanPham);
                    db.SaveChanges();
                    return Json(new { msg = true }, JsonRequestBehavior.AllowGet);
                }
                catch
                {
                    return Json(new { msg = false }, JsonRequestBehavior.AllowGet);

                }
            }
            ViewBag.Maloai_id = new SelectList(db.LoaiSanPhams, "Maloai_id", "Tenloai", sanPham.Maloai_id);

            return Json(new { msg = true }, JsonRequestBehavior.AllowGet);

        }
        public ActionResult SuaSP(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SuaSP([Bind(Include = "sanpham_id,maloai_id,tensanpham,anh,soluong,gia,mota,kichco,dophangiai,giakhuyenmai,Viewcount,ReducePrice")] SanPham sanPham)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.Entry(sanPham).State = EntityState.Modified;
                    db.SaveChanges();
                    return Json(new { msg = true }, JsonRequestBehavior.AllowGet);
                }
                catch
                {
                    return Json(new { msg = true }, JsonRequestBehavior.AllowGet);

                }

            }
            return Json(new { msg = true }, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public ActionResult XoaSP(int id)
        {
            SanPham sanPham = db.SanPhams.Find(id);
            db.SanPhams.Remove(sanPham);
            db.SaveChanges();
            return Json(new { msg = true }, JsonRequestBehavior.AllowGet);
        }
        // GET: Admin/SanPhams/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // GET: Admin/SanPhams/Create
        public ActionResult Create()
        {
            ViewBag.maloai_id = new SelectList(db.LoaiSanPhams, "maloai_id", "tenloai");
            return View();
        }

        // POST: Admin/SanPhams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create([Bind(Include = "sanpham_id,maloai_id,tensanpham,anh,soluong,gia,mota,kichco,dophangiai,giakhuyenmai,Viewcount,ReducePrice")] SanPham sanPham,HttpPostedFileBase file1)
        {
            string _FileName = "";
            string _path = "";
            try
            {
                if (file1.ContentLength > 0)
                {
                    _FileName = Path.GetFileName(file1.FileName);
                    _path = Path.Combine(Server.MapPath("~/Image"), _FileName);
                    file1.SaveAs(_path);
                }
            }
            catch
            {

            }
            if (ModelState.IsValid)
            {
                sanPham.Anh = _FileName;
                db.SanPhams.Add(sanPham);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.maloai_id = new SelectList(db.LoaiSanPhams, "maloai_id", "tenloai", sanPham.Maloai_id);
            return View(sanPham);
        }

        // GET: Admin/SanPhams/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            ViewBag.maloai_id = new SelectList(db.LoaiSanPhams, "maloai_id", "tenloai", sanPham.Maloai_id);
            return View(sanPham);
        }

        // POST: Admin/SanPhams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "sanpham_id,maloai_id,tensanpham,anh,soluong,gia,mota,kichco,dophangiai,giakhuyenmai,Viewcount,ReducePrice")] SanPham sanPham, HttpPostedFileBase file1)
        {
            string _FileName = "";
            string _path = "";
            try
            {
                if (file1.ContentLength > 0)
                {
                    _FileName = Path.GetFileName(file1.FileName);
                    _path = Path.Combine(Server.MapPath("~/Image"), _FileName);
                    file1.SaveAs(_path);
                }
            }
            catch
            {

            }


            if (ModelState.IsValid)
            {
                sanPham.Anh = _FileName;
                db.Entry(sanPham).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.maloai_id = new SelectList(db.LoaiSanPhams, "maloai_id", "tenloai", sanPham.Maloai_id);
            return View(sanPham);
        }

        // GET: Admin/SanPhams/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // POST: Admin/SanPhams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SanPham sanPham = db.SanPhams.Find(id);
            db.SanPhams.Remove(sanPham);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [HttpPost]
        public ContentResult Upload()
        {
            BTL_MVCEntities db = new BTL_MVCEntities();
            try
            {
                string path = Server.MapPath("/Img/");
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }

                foreach (string key in Request.Files)
                {
                    HttpPostedFileBase postFile = Request.Files[key];
                    postFile.SaveAs(path + postFile.FileName);
                    SanPham sp = new SanPham();
                    sp.Anh = postFile.FileName;
                    db.SanPhams.Add(sp);
                    db.SaveChanges();

BTL - MVC/Areas/Admin/Views/SanPhams/Create.cshtml
@model BTL___MVC.Database.SanPham

@{
    ViewBag.Title = "Thêm sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

@section jsFooter{
    <script src="//cdn.ckeditor.com/4.19.1/standard/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('Mota');
    </script>
}

@using (Html.BeginForm("Create", "SanPhams", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>SanPham</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">

            <label class="control-label col-md-2">Mã loại</label>
            <div class="col-md-10">
                @Html.DropDownList("maloai_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Maloai_id, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">

            <label class="control-label col-md-2">Tên sản phẩm</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tensanpham, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tensanpham, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">

            <label class="control-label col-md-2">Ảnh</label>
            <div class="col-md-10">
                <input type="file" id="file1" name="file1" />
            </div>
        </div>


        <div class="form-group">

            <label class="control-label col-md-2">Số lượng</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Soluong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Soluong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">

            <label class="control-label col-md-2">Giá bán</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">

            <label class="control-label col-md-2">Mô tả</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Mota, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mota, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">

            <label class="control-label col-md-2">Kích cỡ</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Kichco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Kichco, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">

            <label class="control-label col-md-2">Độ phân giải</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dophangiai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Dophangiai, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">

            <label class="control-label col-md-2">Gía khuyến mãi</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Giakhuyenmai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Giakhuyenmai, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">

            <label class="control-label col-md-2">Lượt đánh giá</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Viewcount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Viewcount, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">

            <label class="control-label col-md-2">Giảm giá</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReducePrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReducePrice, "", new { @class = "text-danger" })
            </div>
        </div>
        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-light" />
            </div>
        </div>
    </div>

}


<div>
    @Html.ActionLink("Trở lại", "Index")
</div>

BTL - MVC/Areas/Admin/Views/SanPhams/Delete.cshtml
@model BTL___MVC.Database.SanPham

@{
    ViewBag.Title = "Xóa sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>


<div>
    <h4>SanPham</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên sản phẩm
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tensanpham)
        </dd>

        <dt>
            Ảnh
        </dt>

        <dd>
           
            <img src="~/Image/@Model.Anh" style="width: 150px; height : 150px; " />


        </dd>

        <dt>
            Số lượng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Soluong)
        </dd>

        <dt>
            Giá
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gia)
        </dd>

        <dt>
            Mô tả
        </dt>

        <dd>
            @Html.Raw(Model.Mota)
        </dd>
        <dt>
            Kích cỡ
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kichco)
        </dd>
        <dt>
            Độ phân giải
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dophangiai)
        </dd>
        <dt>
            Gía khuyến mãi
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Giakhuyenmai)
        </dd>

        <dt>
            Tên loại
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiSanPham.Tenloai)
        </dd>
        <dt>
            Lượt đánh giá
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Viewcount)
        </dd>
        <dt>
            Giảm giá
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReducePrice)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" />  <hr />
            @Html.ActionLink("Trở lại", "Index")
        </div>
    }
</div>

BTL - MVC/Areas/Admin/Views/SanPhams/Details.cshtml
@model BTL___MVC.Database.SanPham

@{
    ViewBag.Title = "Xem sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<div>
    <h4>SanPham</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            Tên sản phẩm
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tensanpham)
        </dd>

        <dt>
            Ảnh
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.Anh)*@
            <img src="~/Image/@Model.Anh" style="width: 150px; height : 150px; " />
            
        </dd>

        <dt>
            Số lượng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Soluong)
        </dd>

        <dt>
            Giá
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gia)
        </dd>

        <dt>
            Mô tả
        </dt>

        <dd>
            @Html.Raw(Model.Mota)
        </dd>
        <dt>
            Kích cỡ
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kichco)
        </dd>
        <dt>
            Độ phân giải
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dophangiai)
        </dd>
        <dt>
            Gía khuyến mãi
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Giakhuyenmai)
        </dd>

        <dt>
            Tên loại
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiSanPham.Tenloai)
        </dd>
        <dt>
            Lượt đánh giá
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Viewcount)
        </dd>
        <dt>
            Giảm giá
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReducePrice)
        </dd>


    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Sanpham_id })  <hr />
    @Html.ActionLink("Trở lại", "Index")
</p>

BTL - MVC/Areas/Admin/Views/SanPhams/Edit.cshtml
@model BTL___MVC.Database.SanPham

@{
    ViewBag.Title = "Sửa sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

@section jsFooter{
    <script src="//cdn.ckeditor.com/4.19.1/standard/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('Mota');
    </script>
}

@using (Html.BeginForm("Edit", "SanPhams", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>SanPham</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Sanpham_id)

        <div class="form-group">
            @*@Html.LabelFor(model => model.maloai_id, "maloai_id", htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Mã loại</label>
            <div class="col-md-10">
                @Html.DropDownList("maloai_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Maloai_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.tensanpham, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Tên sản phẩm</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tensanpham, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tensanpham, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.anh, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Ảnh</label>
            <div class="col-md-10">
                <input type="file" name="file1" id="file1" />
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.soluong, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Số lượng</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Soluong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Soluong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.gia, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Giá</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.mota, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Mô tả</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Mota, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mota, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">

            <label class="control-label col-md-2">Kích cỡ</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Kichco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Kichco, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">

            <label class="control-label col-md-2">Độ phân giải</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dophangiai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Dophangiai, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">

            <label class="control-label col-md-2">Gía khuyến mãi</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Giakhuyenmai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Giakhuyenmai, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">

            <label class="control-label col-md-2">Lượt đánh giá</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Viewcount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Viewcount, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">

            <label class="control-label col-md-2">Giảm giá</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReducePrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReducePrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở lại", "Index")
</div>

BTL - MVC/Areas/Admin/Views/SanPhams/Index.cshtml
@model IEnumerable<BTL___MVC.Database.SanPham>

@{
    ViewBag.Title = "Quản lý sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink(" Thêm sản phẩm", "Create", null, new { @class = "btn btn-primary fa fa-plus" })
</p>
<div ng-app="myApp" ng-controller="mycontrol">
    <div class="row">
        <div class="col-lg-6">
            <div class="form-group pull-left">
                <label>Search</label>
                <label>
                    <input type="text" class="form-control" ng-model="searchText" />
                </label>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="form-group pull-right">
                Show
                <label>
                    <select class="form-control" ng-model="itemsPerPage">
                        <option ng-value="1">1</option>
                        <option ng-value="2">2</option>
                        <option ng-value="5">5</option>
                        <option ng-value="10">10</option>
                        <option ng-value="25">25</option>
                        <option ng-value="50">50</option>

                    </select>
                </label>
            </div>
        </div>
    </div>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>
                    STT
                </th>
                <th>
                    Mã loại
                </th>
                <th>
                    Mã sản phẩm
                </th>
                <th>
                    Tên sản phẩm
                </th>
                <th>
                    Ảnh
                </th>
                <th>
                    Số lượng
                </th>
                <th>
                    Gía
                </th>
                @*<th>
                        Mô tả
                    </th>*@
                <th>
                    Kích cỡ
                </th>
                <th>
                    Độ phân giải
                </th>
                <th>
                    Gía khuyến mãi
                </th>
                <th>
                    Lượt đánh giá
                </th>
                <th>
                    Giảm giá
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>

            <tr ng-repeat="data in datas | filter : searchText | limitTo: itemsPerPage: (currentPage - 1 ) * itemsPerPage">
                <td>
                    {{$index + 1}}
                </td>
                <td>
                    {{data.Maloai_id}}
                </td>
                <td>
                    @*@Html.DisplayFor(modelItem => item.Sanpham_id)*@
                    {{data.Sanpham_id}}
                </td>
                <td>
                    @*@Html.DisplayFor(modelItem => item.Tensanpham)*@
                    {{data.Tensanpham}}
                </td>
                <td>
                    <img src="~/Content/IMG/{{data.Anh}}" style="width: 150px; height: 150px;" />
                    @*{{data.Anh}}*@


                </td>
                <td>
                    @*@Html.DisplayFor(modelItem => item.Soluong)*@
                    {{data.Soluong}}
                </td>
                <td>
                    @*@Html.FormatValue( data. , "{0:#,##0}")*@

                    {{data.Gia}}
                </td>
                @*<td>
                        @Html.Raw(item.Mota)
                        {{data.Mota}}
                    </td>*@
                <td>
                    @*@Html.DisplayFor(modelItem => item.Kichco)*@
                    {{data.Kichco}}
                </td>
                <td>
                    @*@Html.DisplayFor(modelItem => item.Dophangiai)*@
                    {{data.Dophangiai}}
                </td>
                <td>
                    @*@Html.FormatValue(item.Giakhuyenmai, "{0:#,##0}")*@
                    {{data.Giakhuyenmai}}
                </td>
                <td>
                    @*@Html.DisplayFor(modelItem => item.Viewcount)*@
                    {{data.Viewcount}}
                </td>
                <td>
                    @*@Html.DisplayFor(modelItem => item.ReducePrice)*@
                    {{data.ReducePrice}}
                </td>
                <td>
                    <a href="/Admin/SanPhams/SuaSP/{{data.Sanpham_id}}" class="btn btn-warning fa fa-pencil"></a>
                    @*<a href="/Admin/SanPhams/Delete/{{data.Sanpham_id}}" class="btn btn-danger fa fa-trash"></a>*@
                    <a href="#" class="btn btn-danger fa fa-trash" data-ng-click="delete(data.Sanpham_id)"></a>

                </td>
            </tr>

        </tbody>

    </table>
    <ul uib-pagination total-items="datas.length" class="pagination-sm" ng-model="currentPage" max-size="5" items-per-page="itemsPerPage"  boundary-links="true" num-pages="numPages"></ul>
</div>


@section jsFooter{

    <script>
        var myApp = angular.module("myApp", ['ui.bootstrap']);
        myApp.controller("mycontrol", mycontrol);
        function mycontrol($scope, $http) {
            $http(
                {
                    url: "/Admin/SanPhams/getData",
                    method: "GET"

                }
            ).then(function (res) {
                $scope.datas = res.data;
            });


            $scope.currentPage = 1;
            $scope.itemsPerPage = 10;

            $scope.delete = function (data) {
                debugger
                $http.post('/Admin/SanPhams/XoaSP', { id: data })
                    .then(function (res) {
                        if (res.msg == false) {
                            alert("Xóa bản ghi không thành công");
                        }
                        else {
                            alert("Xóa bản ghi thành công");
                            window.location.href = "/Admin/SanPhams/Index";
                        }
                    });
            };
        }
    </script>
}