BTL - MVC/Areas/Admin/Controllers/NhanViensController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BTL___MVC.Database;
using static System.Net.WebRequestMethods;

namespace BTL___MVC.Areas.Admin.Controllers
{
    public class NhanViensController : Controller
    {
        private BTL_MVCEntities db = new BTL_MVCEntities();

        // GET: Admin/NhanViens
        public ActionResult Index()
        {
            return View(db.NhanViens.ToList());
        }

        // GET: Admin/NhanViens/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhanVien nhanVien = db.NhanViens.Find(id);
            if (nhanVien == null)
            {
                return HttpNotFound();
            }
            return View(nhanVien);
        }

        // GET: Admin/NhanViens/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/NhanViens/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]

        public ActionResult Create([Bind(Include = "nhanvien_id,tennhanvien,ngaysinh,sdt,diachi,email,anh,tendangnhap,matkhau,trangthai")] NhanVien nhanVien, HttpPostedFileBase file1)
        {
            string _FileName = "";
            string _path = "";
            try
            {
                if (file1.ContentLength > 0)
                {
                    _FileName = Path.GetFileName(file1.FileName);
                    _path = Path.Combine(Server.MapPath("~/Image"), _FileName);
                    file1.SaveAs(_path);
                }
            }
            catch
            {

            }
            if (ModelState.IsValid)
            {
                nhanVien.Anh = _FileName;

                db.NhanViens.Add(nhanVien);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(nhanVien);
        }

        // GET: Admin/NhanViens/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhanVien nhanVien = db.NhanViens.Find(id);
            if (nhanVien == null)
            {
                return HttpNotFound();
            }
            return View(nhanVien);
        }

        // POST: Admin/NhanViens/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]

        public ActionResult Edit([Bind(Include = "nhanvien_id,tennhanvien,ngaysinh,sdt,diachi,email,anh,tendangnhap,matkhau,trangthai")] NhanVien nhanVien, HttpPostedFileBase file1)
        {
            string _FileName = "";
            string _path = "";
            try
            {
                if (file1.ContentLength > 0)
                {
                    _FileName = Path.GetFileName(file1.FileName);
                    _path = Path.Combine(Server.MapPath("~/Image"), _FileName);
                    file1.SaveAs(_path);
                }
            }
            catch
            {

            }
            if (ModelState.IsValid)
            {
                nhanVien.Anh = _FileName;
                db.Entry(nhanVien).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(nhanVien);
        }

        // GET: Admin/NhanViens/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhanVien nhanVien = db.NhanViens.Find(id);
            if (nhanVien == null)
            {
                return HttpNotFound();
            }
            return View(nhanVien);
        }

        // POST: Admin/NhanViens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NhanVien nhanVien = db.NhanViens.Find(id);
            db.NhanViens.Remove(nhanVien);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BTL - MVC/Areas/Admin/Views/NhanViens/Create.cshtml
@model BTL___MVC.Database.NhanVien

@{
    ViewBag.Title = "Thêm nhân viên";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Create", "NhanViens", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>NhanVien</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @*@Html.LabelFor(model => model.tennhanvien, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Tên nhân viên</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tennhanvien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tennhanvien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.ngaysinh, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Ngày sinh</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ngaysinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ngaysinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.sdt, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Số điện thoại</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sdt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sdt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.diachi, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Địa chỉ</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Diachi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Diachi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Email</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">

            <label class="control-label col-md-2">Ảnh</label>
            <div class="col-md-10">
                <input type="file" id="file1" name="file1" />
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-light" />
            </div>
        </div>
    </div>
}
<hr />
<div>
    @Html.ActionLink("Trở lại", "Index")
</div>

BTL - MVC/Areas/Admin/Views/NhanViens/Delete.cshtml
@model BTL___MVC.Database.NhanVien

@{
    ViewBag.Title = "Xóa nhân viên";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<div>
    <h4>NhanVien</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên nhân viên
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tennhanvien)
        </dd>

        <dt>
            Ngày sinh
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ngaysinh)
        </dd>

        <dt>
            Số điện thoại
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sdt)
        </dd>

        <dt>
            Địa chỉ
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Diachi)
        </dd>

        <dt>
            Email
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            Ảnh
        </dt>
        <dd>
            <img src="~/Image/@Model.Anh" style="width: 150px; height : 150px; " />
        </dd>
        <dt>
            Tên đăng nhập
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tendangnhap)
        </dd>
        <dt>
            Mật khẩu
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Matkhau)
        </dd>
        <dt>
            Trạng thái
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Trangthai)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-light" /> <hr />
            @Html.ActionLink("Trở lại", "Index")
        </div>
    }
</div>

BTL - MVC/Areas/Admin/Views/NhanViens/Details.cshtml
@model BTL___MVC.Database.NhanVien

@{
    ViewBag.Title = "Xem nhân viên";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<div>
    <h4>NhanVien</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên nhân viên
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tennhanvien)
        </dd>

        <dt>
            Ngày sinh
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ngaysinh)
        </dd>

        <dt>
            Số điện thoại
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sdt)
        </dd>

        <dt>
            Địa chỉ
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Diachi)
        </dd>


        <dt>
            Email
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            Ảnh
        </dt>
        <dd>
            <img src="~/Image/@Model.Anh" style="width: 150px; height : 150px; " />
        </dd>
        <dt>
            Tên đăng nhập
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tendangnhap)
        </dd>
        <dt>
            Mật khẩu
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Matkhau)
        </dd>
        <dt>
            Trạng thái
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Trangthai)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Nhanvien_id }) <hr />
    @Html.ActionLink("Trở lại", "Index")
</p>

BTL - MVC/Areas/Admin/Views/NhanViens/Edit.cshtml
@model BTL___MVC.Database.NhanVien

@{
    ViewBag.Title = "Sửa nhân viên";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Edit", "NhanViens", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>NhanVien</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Nhanvien_id)

        <div class="form-group">
            @*@Html.LabelFor(model => model.tennhanvien, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Tên nhân viên</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tennhanvien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tennhanvien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.ngaysinh, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Ngày sinh</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ngaysinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ngaysinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.sdt, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2" >Số điện thoại</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sdt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sdt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.diachi, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Địa chỉ</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Diachi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Diachi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Email</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">

            <label class="control-label col-md-2">Ảnh</label>
            <div class="col-md-10">
                <input type="file" id="file1" name="file1" />
            </div>
        </div>
        <div class="form-group">
            @*@Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Tên đăng nhập</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tendangnhap, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @*@Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Mật khẩu</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Matkhau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @*@Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Trạng thái</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Trangthai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-light" />
            </div>
        </div>
    </div>
}

<hr />
<div>
    @Html.ActionLink("Trở lại", "Index")
</div>

BTL - MVC/Areas/Admin/Views/NhanViens/Index.cshtml
@model IEnumerable<BTL___MVC.Database.NhanVien>

@{
    ViewBag.Title = "Nhân Viên";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    int tt = 1;
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink(" Thêm nhân viên", "Create", null, new { @class = "btn btn-primary fa fa-plus" })
</p>
<table class="table table-bordered table-striped" id="dataTable">
    <thead>
        <tr>
            <th>
                STT
            </th>
            <th>
                Mã nhân viên
            </th>
            <th>
                Tên nhân viên
            </th>
            <th>
                Ngày sinh
            </th>
            <th>
                Số điện thoại
            </th>
            <th>
                Địa chỉ
            </th>
            <th>
                Email
            </th>
            <th>
                Ảnh
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @(tt++)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nhanvien_id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tennhanvien)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ngaysinh)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Sdt)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Diachi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @if (item.Anh != null)
                    {
                        <img src="~/Image/@item.Anh" style="width:100px;" />

                    }
                    else
                    {
                        <img src="~/Image/user.png" style="width: 100px;" />

                    }
                </td>
                
                <td>
                    @Html.ActionLink(" ", "Edit", new { id = item.Nhanvien_id }, new { @class = "btn btn-warning fa fa-pencil" }) |
                    @Html.ActionLink(" ", "Details", new { id = item.Nhanvien_id }, new { @class = "btn btn-info fa fa-eye" }) |
                    @Html.ActionLink(" ", "Delete", new { id = item.Nhanvien_id }, new { @class = "btn btn-danger fa fa-trash" })
                </td>
            </tr>
        }
    </tbody>



</table>



@section jsFooter{
    <script src="~/Assets/admin/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Assets/admin/vendor/datatables/dataTables.bootstrap4.min.js"></script>
    <script src="~/Assets/admin/js/demo/datatables-demo.js"></script>
}